In [1]:
n=8j
print(type(8j))

<class 'complex'>


In [34]:
thickness=int(input())
c='S'

# top cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)  + c + (c*i).ljust(thickness-1))

# top pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2) + (c*thickness).center(thickness*6))
    
for i in range(int((thickness+1)/2)):
    print((c*thickness*5).center(thickness*6))

# lower pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2) + (c*thickness).center(thickness*6))

# Lower cone
for i in range(thickness):
    print(((c * (thickness - i - 1)).rjust(thickness) + c +
          (c * (thickness - i - 1)).ljust(thickness)).rjust(thickness*6))

5
    S    
   SSS   
  SSSSS  
 SSSSSSS 
SSSSSSSSS
  SSSSS               SSSSS             
  SSSSS               SSSSS             
  SSSSS               SSSSS             
  SSSSS               SSSSS             
  SSSSS               SSSSS             
  SSSSS               SSSSS             
  SSSSSSSSSSSSSSSSSSSSSSSSS   
  SSSSSSSSSSSSSSSSSSSSSSSSS   
  SSSSSSSSSSSSSSSSSSSSSSSSS   
  SSSSS               SSSSS             
  SSSSS               SSSSS             
  SSSSS               SSSSS             
  SSSSS               SSSSS             
  SSSSS               SSSSS             
  SSSSS               SSSSS             
                    SSSSSSSSS 
                     SSSSSSS  
                      SSSSS   
                       SSS    
                        S     


In [31]:
# Lower pillars
for i in range(thickness):
    print(((c * (thickness - i - 1)).rjust(thickness) + c +
          (c * (thickness - i - 1)).ljust(thickness)).rjust(thickness*6))

                    SSSSSSSSS 
                     SSSSSSS  
                      SSSSS   
                       SSS    
                        S     


In [1]:
import textwrap
def wrap(s,w):
    return textwrap.fill(s,w)

st,wd=input("enter string"),int(input("enter width"))
print(wrap(st,wd))

enter stringuytrewaAZXCVBHJOIUYTEASDFGHJIKwstyyugiolk
enter width6
uytrew
aAZXCV
BHJOIU
YTEASD
FGHJIK
wstyyu
giolk


In [3]:
# number to decimal  binary octal hexadecimal
def fun(number):
    for i in range(number):
        print("{}{}{}{}".format(i,oct(i),hex(i),bin(i)))

fun(25)


00o00x00b0
10o10x10b1
20o20x20b10
30o30x30b11
40o40x40b100
50o50x50b101
60o60x60b110
70o70x70b111
80o100x80b1000
90o110x90b1001
100o120xa0b1010
110o130xb0b1011
120o140xc0b1100
130o150xd0b1101
140o160xe0b1110
150o170xf0b1111
160o200x100b10000
170o210x110b10001
180o220x120b10010
190o230x130b10011
200o240x140b10100
210o250x150b10101
220o260x160b10110
230o270x170b10111
240o300x180b11000


In [ ]:
print("{0:{1}}{0:{1}o}{0:{1}X}{0:{1}b}".format(i,len("{0:b}".format(number))))

In [6]:
# number to decimal  binary octal hexadecimal
def fun(number):
    for i in range(number):
        print("{0:{1}}{0:{1}o}{0:{1}X}{0:{1}b}".format(i,len("{0:b}".format(number))+3))

fun(25)

       0       0       0       0
       1       1       1       1
       2       2       2      10
       3       3       3      11
       4       4       4     100
       5       5       5     101
       6       6       6     110
       7       7       7     111
       8      10       8    1000
       9      11       9    1001
      10      12       A    1010
      11      13       B    1011
      12      14       C    1100
      13      15       D    1101
      14      16       E    1110
      15      17       F    1111
      16      20      10   10000
      17      21      11   10001
      18      22      12   10010
      19      23      13   10011
      20      24      14   10100
      21      25      15   10101
      22      26      16   10110
      23      27      17   10111
      24      30      18   11000


In [7]:
# capitalisingg the  first letter
def capitalise(s):
    l=len(s)
    s1=s[0].upper()
    for i  in range(l):
        if s[i-1]==' ':
            s1=s1+s[i].upper()
        else:
            s1=s1+s[i]
    return s1

print(capitalise("helloeee jibc dhic oidin j  n  uhue   eheud9"))
            


Hhelloeee Jibc Dhic Oidin J  N  Uhue   Eheud9


In [17]:
# omit simultaneos dublicates and wrap with width = k

from collections import OrderedDict 
s="AABCAAADA"
k=int(2)
l=[s[i:i+k] for i in range(0,len(s),k)]

In [18]:
l

['AA', 'BC', 'AA', 'AD', 'A']

In [19]:
for st in l:
    print("".join(OrderedDict.fromkeys(st)))

A
BC
A
AD
A


In [20]:
import numpy as np

In [26]:

ar=np.array([[4,5,52,6],[45,68,35,98]])
print(ar.shape)

(2, 4)


In [28]:
tr=np.transpose(ar)
print(ar)

[[ 4  5 52  6]
 [45 68 35 98]]


In [32]:
flat=ar.flatten()
print(flat)

[ 4  5 52  6 45 68 35 98]


In [35]:
r,c=map(int,input().split())
arr=np.array(list(input().split()for i in range(r)))
print(arr)
print(np.transpose(arr))
print(arr.flatten())

4 4
4 5 6 7
1 2 3 4 
6 4 5 4
     78 9 5  4
[['4' '5' '6' '7']
 ['1' '2' '3' '4']
 ['6' '4' '5' '4']
 ['78' '9' '5' '4']]
[['4' '1' '6' '78']
 ['5' '2' '4' '9']
 ['6' '3' '5' '5']
 ['7' '4' '4' '4']]
['4' '5' '6' '7' '1' '2' '3' '4' '6' '4' '5' '4' '78' '9' '5' '4']


In [36]:
r,c=map(int,input().split())
arr=np.array(list(input().split()for i in range(r)),int)
print(arr)
print(np.transpose(arr))
print(arr.flatten())

2 2
45 56 
65  54
[[45 56]
 [65 54]]
[[45 65]
 [56 54]]
[45 56 65 54]


In [37]:
import random
for _ in range(5):
    print(random.randint(1,65))

11
41
24
21
55


In [38]:
data=np.random.randn(3,2)

In [39]:
data

array([[ 1.80443434,  0.09828497],
       [-0.18514707, -1.42023709],
       [-0.93408418,  0.82869884]])

In [43]:
print(data.mean(),data.min(),data.max())
print(data.T)

0.031991633998327405 -1.4202370916860878 1.8044343400488732
[[ 1.80443434 -0.18514707 -0.93408418]
 [ 0.09828497 -1.42023709  0.82869884]]


In [ ]:
dataa=np.random.randint(1,200)

In [18]:
import random
import string 




def rand_pass(size):  
    # Takes random choices from  
	# ascii_letters and digits  
	generate_pass = ''.join([random.choice( string.ascii_uppercase +
		                            string.ascii_lowercase +
		                            string.digits)  
		                            for n in range(size)])
	return generate_pass


# Driver Code   
password = rand_pass(5)

print(password)
print(type(password))

payload = "{ \"sender\": \"SOCKET\", \"route\": \"4\", \"country\": \"91\", \"sms\": [ { \"message\": \"It will send yor otp ..\" "+password+", \"to\": [ \"6392741843\" ] } ] }"



print(payload)

Sabg8
<class 'str'>
{ "sender": "SOCKET", "route": "4", "country": "91", "sms": [ { "message": "It will send yor otp .." Sabg8, "to": [ "6392741843" ] } ] }


In [13]:
print(type(payload))

<class 'str'>
